import Link from "next/link";

import { BrainCircuit, Database, Sparkles, ArrowRight } from "lucide-react";

export default function Home() {
  return (
    <main className="min-h-screen bg-black text-white selection:bg-white/20">
      <div className="max-w-5xl mx-auto px-6 pt-32 pb-20">

        {/* Hero Section */}
        <section className="text-center mb-32 space-y-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-medium text-gray-400 mb-4 animate-fade-in-up">
            <Sparkles className="w-3 h-3" />
            <span>Powered by Gemini 2.0 Flash</span>
          </div>

          <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-6 bg-clip-text text-transparent bg-gradient-to-b from-white to-gray-500 pb-2">
            AI-powered insights for <br /> your career readiness.
          </h1>

          <p className="text-gray-400 text-lg md:text-xl max-w-2xl mx-auto leading-relaxed">
            Career Compass evaluates your profile using advanced machine learning models
            to provide actionable feedback for your professional growth.
          </p>

          <div className="pt-8">
            <Link
              href="/predict"
              className="group inline-flex items-center gap-2 bg-white text-black px-8 py-4 rounded-full font-semibold hover:opacity-90 transition-all active:scale-95"
            >
              Analyze Your Profile
              <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
        </section>

        {/* Features Grid */}
        <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <FeatureCard
            icon={<Database className="w-6 h-6 text-gray-400" />}
            title="Structured Input"
            desc="Easily input your skills, projects, and experiences in a simple, structured format."
          />
          <FeatureCard
            icon={<BrainCircuit className="w-6 h-6 text-gray-400" />}
            title="ML Evaluation"
            desc="Our trained model analyzes your profile against industry standards to predict readiness."
          />
          <FeatureCard
            icon={<Sparkles className="w-6 h-6 text-gray-400" />}
            title="AI Explanation"
            desc="Get detailed, personalized feedback and improvement tips generated by Gemini AI."
          />
        </section>
      </div>
    </main>
  );
}

function FeatureCard({ icon, title, desc }) {
  return (
    <div className="p-8 rounded-2xl border border-white/10 bg-white/5 hover:bg-white/10 transition-colors duration-300">
      <div className="mb-4">{icon}</div>
      <h3 className="text-xl font-semibold mb-3 text-white">{title}</h3>
      <p className="text-gray-400 leading-relaxed text-sm">{desc}</p>
    </div>
  );
}
