"use client";

import { useSearchParams } from "next/navigation";
import Link from "next/link";
import {
    ArrowRight,
    RotateCcw,
    ShieldCheck,
    AlertTriangle,
    XCircle,
    Info
} from "lucide-react";

export default function InsightsClient() {
    const searchParams = useSearchParams();

    const level = searchParams.get("level") || "Unknown";
    const explanation = searchParams.get("explanation");

    let levelColor = "text-gray-400 border-gray-400";
    let LevelIcon = Info;

    if (level.toLowerCase().includes("high")) {
        levelColor = "text-green-400 border-green-500/50 bg-green-500/10";
        LevelIcon = ShieldCheck;
    } else if (
        level.toLowerCase().includes("medium") ||
        level.toLowerCase().includes("moderate")
    ) {
        levelColor = "text-yellow-400 border-yellow-500/50 bg-yellow-500/10";
        LevelIcon = AlertTriangle;
    } else if (level.toLowerCase().includes("low")) {
        levelColor = "text-red-400 border-red-500/50 bg-red-500/10";
        LevelIcon = XCircle;
    }

    if (!explanation) {
        return (
            <main className="min-h-screen bg-black text-white flex items-center justify-center p-6">
                <div className="text-center space-y-4">
                    <p className="text-gray-400">
                        No insights available. Please run an analysis first.
                    </p>
                    <Link
                        href="/predict"
                        className="inline-flex items-center gap-2 px-6 py-2 border border-white/20 rounded-full hover:bg-white hover:text-black transition-all"
                    >
                        Go to Predict
                    </Link>
                </div>
            </main>
        );
    }

    return (
        <main className="min-h-screen bg-black text-white pt-32 pb-20">
            <div className="max-w-4xl mx-auto px-6">
                {/* Header */}
                <section className="mb-12 text-center">
                    <h1 className="text-4xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-gray-400">
                        Career Insights
                    </h1>
                    <p className="text-gray-400 max-w-2xl mx-auto leading-relaxed">
                        Based on your provided metrics, our AI has analyzed your
                        career readiness profile.
                    </p>
                </section>

                <div className="grid gap-8">
                    {/* Readiness Card */}
                    <section className="bg-white/5 border border-white/10 p-8 rounded-3xl backdrop-blur-sm shadow-2xl">
                        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
                            <div>
                                <h2 className="text-sm font-medium uppercase tracking-widest text-gray-500 mb-2">
                                    Overall Readiness
                                </h2>
                                <div
                                    className={`inline-flex items-center gap-2 px-4 py-1.5 rounded-full border ${levelColor}`}
                                >
                                    <LevelIcon className="w-5 h-5" />
                                    <span className="font-semibold">
                                        {level}
                                    </span>
                                </div>
                            </div>

                            <div className="h-px md:h-12 w-full md:w-px bg-white/10" />

                            <div className="text-center md:text-right">
                                <p className="text-sm text-gray-400">
                                    Analysis complete
                                </p>
                                <p className="text-xs text-gray-600">
                                    Generated by Gemini
                                </p>
                            </div>
                        </div>
                    </section>

                    {/* Explanation */}
                    <section className="bg-white/5 border border-white/10 p-8 rounded-3xl backdrop-blur-sm">
                        <h2 className="text-lg font-semibold mb-6 flex items-center gap-2">
                            <Info className="w-5 h-5 text-blue-400" />
                            AI Explanation & Recommendations
                        </h2>
                        <div className="prose prose-invert max-w-none text-gray-300 leading-7 whitespace-pre-line">
                            {explanation}
                        </div>
                    </section>

                    {/* Actions */}
                    <div className="flex justify-center gap-4 pt-4">
                        <Link
                            href="/predict"
                            className="px-6 py-3 rounded-xl border border-white/20 hover:bg-white/5 flex items-center gap-2 transition-colors"
                        >
                            <RotateCcw className="w-4 h-4" />
                            Run Again
                        </Link>

                        <Link
                            href="/"
                            className="px-6 py-3 rounded-xl bg-white text-black font-semibold hover:opacity-90 flex items-center gap-2 transition-all active:scale-95"
                        >
                            Back to Home
                            <ArrowRight className="w-4 h-4" />
                        </Link>
                    </div>
                </div>
            </div>
        </main>
    );
}
